version: '3.8'

services:
  openvpn:
    image: andreusimus3/my-custom-openvpn
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - 1194:1194
    volumes:
      - ./openvpn-data/conf:/etc/openvpn
    restart: unless-stopped
    environment:
      - DEBUG=1 